# Use postgres/example user/password credentials
version: "3.4"

services:   
  build:
    image: node:16-alpine3.11
    command: ci/build.sh
    user: ${CURRENT_UID-0:0}
    working_dir: /code
    volumes:
      - "${PROJECT_DIR}:/code"
  
  test:
    image: node:16-alpine3.11
    command: ci/test.sh
    user: ${CURRENT_UID-0:0}
    working_dir: /code
    volumes:
      - "${PROJECT_DIR}:/code"

  service:
    image: node:16-alpine3.11
    command: ci/service.sh
    user: ${CURRENT_UID-0:0}
    working_dir: /code
    volumes:
      - "${PROJECT_DIR}:/code"
    ports:
      - 5000:5000
  